name: Deploy Python Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - python/**

defaults:
  run:
    working-directory: ./python

jobs:
  build_deployment_artifacts:
    name: Build Artifacts
    uses: ./.github/workflows/python-build-and-lint.yml

  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-22.04
    needs: build_deployment_artifacts
    steps:
      - name: Get ${{ github.event.repository.name }} Package Version
        id: package-version
        run: |
          VERSION=$(pip show ${{ github.event.repository.name }} | grep Version | cut -f 2 -d " ")
          echo VERSION_STRING=$VERSION >> $GITHUB_OUTPUT

      - name: Download Python Wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{steps.package-version.outputs.VERSION_STRING}}_wheel
          path: python/dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
