name: Deploy Python Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - python/**

defaults:
  run:
    working-directory: ./python

jobs:
  build_deployment_artifacts:
    name: Build Artifacts
    uses: ./.github/workflows/python-build-and-lint.yml

  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-22.04
    needs: build_deployment_artifacts
    permissions:
      # Important:  This permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download Python Wheel
        uses: actions/download-artifact@v3
        with:
          name: aac_spec_wheel
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
